apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  labels:
    testing.upbound.io/name: myvm-subnet
  name: myvm-subnet
spec:
  providerConfigRef:
    name: default
  forProvider:
    availabilityZone: us-west-2a
    cidrBlock: 172.16.10.0/24
    region: us-west-2
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/name: myvm-vpc
